version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/dMLPA-flask/
      - /var/local/dMLPA-flask/logs/:/var/local/dMLPA-flask/logs/
      - /var/local/dMLPA-flask/probe_file/:/var/local/dMLPA-flask/probe_file/
      - /var/local/dMLPA-flask/inputs/:/var/local/dMLPA-flask/inputs/
      - /var/local/dMLPA-flask/outputs/:/var/local/dMLPA-flask/outputs/

    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=/dMLPA-flask/dMLPA-flask/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONPATH=/dMLPA-flask/dMLPA-flask
